version: "3.2"
services:
  php-apache:
    build:
      context: './booked-2.7.8/'
      args:
        PHP_MOD: ${PHP_MOD}
        PHP_VERSION: ${PHP_VERSION}
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    container_name: booked-php-apache
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3306:3306"
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    container_name: booked-db
networks:
  frontend:
  backend:

